import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBarWrapper } from "@/components/Providers/NavBarWrapper";
import Providers from "@/components/Providers/Providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased h-full`}>
        <Providers>
          <NavBarWrapper>{children}</NavBarWrapper>
        </Providers>
      </body>
    </html>
  );
}
